
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_collection
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  auth_service:
    build: ./auth_service
    container_name: auth_service
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=data_collection
      - JWT_SECRET_KEY=supersecretkey

    depends_on:
      - mysql

  enter_data:
    build: ./enter_data
    container_name: enter_data
    restart: always
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=data_collection
      - PORT=5002
    depends_on:
      - mysql
      - auth_service

volumes:
  mysql_data:
  mongo_data:

networks:
  default:
    driver: bridge

