CREATE DATABASE IF NOT EXISTS data_collection;
USE data_collection;

CREATE TABLE IF NOT EXISTS weather_readings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  city VARCHAR(64) NOT NULL,
  temp_c DECIMAL(5,2) NOT NULL,
  humidity_pct INT UNSIGNED,
  recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
